version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    command: sh -c "npm install express --save && npm install mysql && npm install node-random-name && node index.js"
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true

    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./sql/initdb.sql:/docker-entrypoint-initdb.d/0_init.sql:rw    
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
    build: 
      context: nginx
    image: nginx
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
       - app   

    

networks: 
  node-network:
    driver: bridge      
